config/routes.rb
Cas::Application.routes.draw do
  get "sign_in/start"
  get "sign_in/index"
  get 'sign_in' => 'sign_in#index'

  get "sign_in/logout"
  get "sign_in/web_service(.:format)"
  match "/cas_proxy_callback/:action" => "cas_proxy_callback", via: [:get, :post]

  root 'sign_in#start'

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/sign_in_controller.rb
class SignInController < ApplicationController
#  before_filter RubyCas::Filter
  before_filter CASClient::Frameworks::Rails::Filter, :except => [:start]

  def start
  end
  
  def index
	self.allow_forgery_protection = false
	service_uri = "https://inside-d.cc.nd.edu"
	@proxy_granting_ticket = session[:cas_pgt]
	@proxy_ticket = CASClient::Frameworks::Rails::Filter.client.proxy_callback_url
  end

  def web_service
    respond_to do |format|
      format.json { render :json => session}
      format.xml  { render :xml => session, :content_type => "application/xml"}
    end
  end

  def logout
	self.allow_forgery_protection = false
	CASClient::Frameworks::Rails::Filter.logout(self)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sign_in_helper.rb
module SignInHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cas</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sign_in/index.html.erb
<h1>SignIn#index</h1>
<p>Find me in app/views/sign_in/index.html.erb</p>
<%= link_to "Logout", sign_in_logout_path %>

<ul>
<li>CAS user: <%= session[:cas_user] %></li>
<li>CAS ticket: <%= session[:cas_pgt] %></li>
<li><%= debug CASClient::Frameworks::Rails::Filter.client %></li>
<li><%= debug session %></li>
</ul>

app/views/sign_in/start.html.erb
<%= link_to "Go sign in to CAS", sign_in_path %>